name: Install and Run AnyDesk

on:
  push:
    branches:
      - main

jobs:
  install_and_run_anydesk:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the PowerShell script
      run: |
        echo '$installerUrl = "https://download.anydesk.com/AnyDesk.exe"' > install_anydesk.ps1
        echo '$installerPath = "$env:TEMP\AnyDesk.exe"' >> install_anydesk.ps1
        echo 'Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath' >> install_anydesk.ps1
        echo 'Start-Process -FilePath $installerPath -ArgumentList "/install /silent" -Wait' >> install_anydesk.ps1
        echo 'Start-Process -FilePath "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"' >> install_anydesk.ps1
        echo 'Start-Sleep -Seconds 5' >> install_anydesk.ps1
        echo '$logPath = "$env:PROGRAMDATA\AnyDesk\ad_svc.trace"' >> install_anydesk.ps1
        echo '$anydeskId = Select-String -Path $logPath -Pattern ".*my anydesk address.*" | ForEach-Object { $_.Matches.Groups[0].Value } | Select-String -Pattern "\d{9}" | Select-Object -First 1' >> install_anydesk.ps1
        echo 'Write-Output "AnyDesk ID: $anydeskId"' >> install_anydesk.ps1

    - name: Run AnyDesk Script
      run: PowerShell -ExecutionPolicy Bypass -File ./install_anydesk.ps1
