name: Setup Kali Linux with Ngrok for RDP

on:
  push:
    branches:
      - main

jobs:
  setup_kali_ngrok:
    runs-on: [self-hosted, kali-linux]  # Adjust this based on your self-hosted runner configuration

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ngrok
      run: |
        # Define paths and URLs
        $ngrokUrl = "https://bin.equinox.io/c/4b0ac842e8e3/ngrok-stable-linux-amd64.zip" # Latest Ngrok URL for Linux
        $ngrokPath = "$HOME/ngrok.zip"
        $ngrokExePath = "$HOME/ngrok"

        # Download and install Ngrok
        wget $ngrokUrl -O $ngrokPath
        unzip $ngrokPath -d $HOME

        # Configure Ngrok with the auth token
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Setup RDP
      run: |
        # Install xrdp for RDP access
        sudo apt-get update
        sudo apt-get install -y xrdp

        # Start the xrdp service
        sudo systemctl start xrdp
        sudo systemctl enable xrdp

        # Configure RDP access (optional configurations)
        sudo ufw allow 3389/tcp

    - name: Start Ngrok Tunnel for RDP
      run: |
        # Start Ngrok to tunnel RDP port (3389)
        ngrok tcp 3389 &

        # Wait for Ngrok to establish the tunnel
        sleep 10

        # Retrieve Ngrok public URL
        ngrokApiUrl="http://localhost:4040/api/tunnels"
        ngrokTunnel=$(curl -s $ngrokApiUrl | jq -r '.tunnels[0].public_url')

        # Output the Ngrok URL for RDP
        echo "Ngrok public URL for RDP access: $ngrokTunnel"
