name: Setup Minecraft Bedrock Server 1.10 and Retrieve Public IP

on:
  push:
    branches:
      - main

jobs:
  setup_minecraft_server:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl

    - name: Download Minecraft Bedrock Server 1.10
      run: |
        # Define paths and URLs
        SERVER_URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.10.0.7.zip"
        SERVER_ZIP="bedrock-server-1.10.0.7.zip"
        SERVER_PATH="/home/runner/minecraft-bedrock"

        # Download and extract Minecraft Bedrock server
        wget $SERVER_URL -O $SERVER_ZIP
        mkdir -p $SERVER_PATH
        unzip $SERVER_ZIP -d $SERVER_PATH

    - name: Start Minecraft Bedrock Server
      run: |
        # Navigate to the server directory
        cd $SERVER_PATH

        # Start the Minecraft Bedrock server in the background
        nohup ./bedrock_server > /dev/null 2>&1 &

    - name: Retrieve Public IP Address
      run: |
        # Wait for a short period to ensure the server has started
        sleep 10
        
        # Retrieve and print the public IP address
        PUBLIC_IP=$(curl -s ifconfig.me)
        echo "Public IP Address: $PUBLIC_IP"
