name: Setup Minecraft Server and Expose with Ngrok

on:
  push:
    branches:
      - main

jobs:
  setup_minecraft_server:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        @powershell -NoProfile -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

    - name: Install Node.js
      run: choco install nodejs-lts

    - name: Download Ngrok and Minecraft Server
      run: |
        echo 'Downloading and installing Ngrok and Minecraft Bedrock server...' > setup_minecraft_server.ps1
        echo 'Invoke-WebRequest -Uri "https://bin.equinox.io/c/4b0ac842e8e3/ngrok-stable-windows-amd64.zip" -OutFile "$env:TEMP\ngrok.zip"' >> setup_minecraft_server.ps1
        echo 'Expand-Archive -Path "$env:TEMP\ngrok.zip" -DestinationPath $env:TEMP' >> setup_minecraft_server.ps1
        echo 'Invoke-WebRequest -Uri "https://minecraft.net/download/server/bedrock" -OutFile "$env:TEMP\minecraft-bedrock-server.zip"' >> setup_minecraft_server.ps1
        echo 'Expand-Archive -Path "$env:TEMP\minecraft-bedrock-server.zip" -DestinationPath "$env:TEMP\minecraft-bedrock"' >> setup_minecraft_server.ps1
        echo 'Start-Process -FilePath "$env:TEMP\ngrok.exe" -ArgumentList "authtoken <YOUR_NGROK_AUTH_TOKEN>" -NoNewWindow -PassThru' >> setup_minecraft_server.ps1
        echo 'Start-Process -FilePath "$env:TEMP\minecraft-bedrock\bedrock_server.exe" -NoNewWindow -PassThru' >> setup_minecraft_server.ps1
        echo 'Start-Sleep -Seconds 30' >> setup_minecraft_server.ps1
        echo 'Start-Process -FilePath "$env:TEMP\ngrok.exe" -ArgumentList "tcp 19132" -NoNewWindow -PassThru' >> setup_minecraft_server.ps1
        echo 'Start-Sleep -Seconds 10' >> setup_minecraft_server.ps1
        echo '$ngrokApiUrl = "http://localhost:4040/api/tunnels"' >> setup_minecraft_server.ps1
        echo '$ngrokTunnel = (Invoke-RestMethod -Uri $ngrokApiUrl).tunnels[0].public_url' >> setup_minecraft_server.ps1
        echo 'Write-Output "Minecraft Bedrock server is running."' >> setup_minecraft_server.ps1
        echo 'Write-Output "Join the server using the following URL: $ngrokTunnel"' >> setup_minecraft_server.ps1

    - name: Run Minecraft Server Setup Script
      run: PowerShell -ExecutionPolicy Bypass -File ./setup_minecraft_server.ps1
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
