name: Enable RDP and Retrieve Login Info

on:
  push:
    branches:
      - main

jobs:
  enable_rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the PowerShell script
      run: |
        echo 'Set-ItemProperty -Path ''HKLM:\System\CurrentControlSet\Control\Terminal Server'' -Name "fDenyTSConnections" -Value 0' > enable_rdp.ps1
        echo 'Enable-NetFirewallRule -DisplayGroup "Remote Desktop"' >> enable_rdp.ps1
        echo '$ipAddress = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Ethernet").IPAddress' >> enable_rdp.ps1
        echo 'if (-not $ipAddress) {$ipAddress = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Wi-Fi").IPAddress}' >> enable_rdp.ps1
        echo '$username = $env:USERNAME' >> enable_rdp.ps1
        echo '$hostname = $env:COMPUTERNAME' >> enable_rdp.ps1
        echo 'Write-Output "RDP is enabled on this machine."' >> enable_rdp.ps1
        echo 'Write-Output "Use the following login information to connect via RDP:"' >> enable_rdp.ps1
        echo 'Write-Output "IP Address: $ipAddress"' >> enable_rdp.ps1
        echo 'Write-Output "Username: $username"' >> enable_rdp.ps1
        echo 'Write-Output "Hostname: $hostname"' >> enable_rdp.ps1

    - name: Run RDP Script
      run: PowerShell -ExecutionPolicy Bypass -File ./enable_rdp.ps1
