name: Install and Run AnyDesk

on:
  push:
    branches:
      - main

jobs:
  install_and_run_anydesk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the script
      run: |
        echo '#!/bin/bash' > install_anydesk.sh
        echo 'sudo apt-get update -y' >> install_anydesk.sh
        echo 'wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -' >> install_anydesk.sh
        echo 'echo "deb http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk.list' >> install_anydesk.sh
        echo 'sudo apt-get update -y' >> install_anydesk.sh
        echo 'sudo apt-get install -y anydesk' >> install_anydesk.sh
        echo 'anydesk &' >> install_anydesk.sh
        echo 'sleep 5' >> install_anydesk.sh
        echo 'anydesk_id=$(anydesk --get-id)' >> install_anydesk.sh
        echo 'echo "AnyDesk ID: $anydesk_id"' >> install_anydesk.sh
        chmod +x install_anydesk.sh

    - name: Run AnyDesk Script
      run: ./install_anydesk.sh
